# Generated by Django 2.0.1 on 2018-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180306_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
