# Generated by Django 2.0.1 on 2018-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.NullBooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
